SELECT COUNCIL.COMPREHENSIVE_OBS_HAUL.CRUISE,
  CAST(COUNCIL.COMPREHENSIVE_OBS_HAUL.HAUL_JOIN AS VARCHAR(20)) AS HAUL_JOIN,
  COUNCIL.COMPREHENSIVE_OBS_HAUL.TARGET_FISHERY_NAME,
  COUNCIL.COMPREHENSIVE_OBS_HAUL.TRIP_TARGET_NAME
FROM COUNCIL.COMPREHENSIVE_OBS_HAUL
WHERE COUNCIL.COMPREHENSIVE_OBS_HAUL.YEAR
    -- insert year
    