SELECT
      CASE 
        WHEN OBSINT.DEBRIEFED_LENGTH.GEAR in (1,2,3,4) 
        THEN 'TRW'
        WHEN OBSINT.DEBRIEFED_LENGTH.GEAR in 6 
        THEN 'POT' 
        WHEN OBSINT.DEBRIEFED_LENGTH.GEAR in (5,7,9,10,11,68,8) 
        THEN 'HAL' 
      END                                              AS GEAR, 
      CONCAT('H',TO_CHAR(OBSINT.DEBRIEFED_SPCOMP.HAUL_JOIN))  AS HAUL_JOIN, 
      TO_CHAR(OBSINT.DEBRIEFED_SPCOMP.HAUL_DATE, 'MM') AS MONTH, 
      TO_CHAR(OBSINT.DEBRIEFED_SPCOMP.HAUL_DATE, 'YYYY') AS YEAR,
      OBSINT.DEBRIEFED_LENGTH.SPECIES AS SPECIES,
      OBSINT.DEBRIEFED_SPCOMP.EXTRAPOLATED_NUMBER        AS NUMB, 
      OBSINT.DEBRIEFED_SPCOMP.CRUISE        AS CRUISE, 
      OBSINT.DEBRIEFED_SPCOMP.PERMIT        AS PERMIT, 
      OBSINT.DEBRIEFED_SPCOMP.HAUL        AS HAUL, 
      OBSINT.DEBRIEFED_SPCOMP.EXTRAPOLATED_WEIGHT,
      CASE 
        WHEN OBSINT.DEBRIEFED_LENGTH.SEX IN 'F'
        THEN '1'
        WHEN OBSINT.DEBRIEFED_LENGTH.SEX IN 'M'
        THEN '2'
        WHEN OBSINT.DEBRIEFED_LENGTH.SEX IN 'U'
        THEN '3'
      END  AS SEX,
      OBSINT.DEBRIEFED_LENGTH.LENGTH                     AS LENGTH, 
      OBSINT.DEBRIEFED_LENGTH.FREQUENCY                  AS sum_frequency, 
      OBSINT.DEBRIEFED_SPCOMP.HAUL_DATE AS HDAY, 
      OBSINT.DEBRIEFED_HAUL.NMFS_AREA AS AREA, 
      OBSINT.DEBRIEFED_HAUL.CATCHER_BOAT_ADFG AS VES_AKR_ADFG,
      'DOMESTIC' AS SOURCE 
FROM OBSINT.DEBRIEFED_HAUL 
  INNER JOIN OBSINT.DEBRIEFED_SPCOMP 
  ON OBSINT.DEBRIEFED_HAUL.HAUL_JOIN = OBSINT.DEBRIEFED_SPCOMP.HAUL_JOIN 
  INNER JOIN OBSINT.DEBRIEFED_LENGTH 
  ON OBSINT.DEBRIEFED_HAUL.HAUL_JOIN = OBSINT.DEBRIEFED_LENGTH.HAUL_JOIN 
WHERE 
       OBSINT.DEBRIEFED_HAUL.NMFS_AREA 
         -- insert region
      AND OBSINT.DEBRIEFED_SPCOMP.SPECIES  
          -- insert species
      AND OBSINT.DEBRIEFED_LENGTH.SPECIES 
          -- insert species