SELECT s.REGION, 
	TO_CHAR(h.START_TIME, 'yyyy') AS YEAR, 
	s.CRUISEJOIN, 
	s.CRUISE, 
	h.VESSEL, 
	s.HAULJOIN, 
	s.HAUL, 
	s.SPECIES_CODE, 
	s.LENGTH, 
	s.SEX, 
	s.WEIGHT, 
	s.MATURITY, 
	s.AGE, 
	h.END_LATITUDE, 
	h.END_LONGITUDE, 
	h.HAUL_TYPE, 
	h.GEAR, 
	h.PERFORMANCE, 
	s.SPECIMEN_SAMPLE_TYPE, 
	s.SPECIMENID, 
	s.BIOSTRATUM
 FROM RACEBASE.SPECIMEN s 
 	INNER JOIN RACEBASE.HAUL h 
 	ON s.HAULJOIN = h.HAULJOIN AND s.CRUISEJOIN = h.CRUISEJOIN 
  	JOIN RACE_DATA.V_CRUISES v 
 	ON h.CRUISEJOIN = v.CRUISEJOIN 
 WHERE 
 v.SURVEY_DEFINITION_ID  
 -- insert survey
 AND h.STATIONID IS NOT NULL 
 AND h.HAUL_TYPE = 3 
 AND h.PERFORMANCE >= 0 
 AND TO_CHAR(h.START_TIME, 'yyyy') 
  -- insert start_year
 AND s.REGION  
 -- insert area
 AND s.SPECIES_CODE 
 -- insert species
 ORDER BY s.SPECIES_CODE, 
 	TO_CHAR(h.START_TIME, 'yyyy'), 
	s.SEX, 
 	s.AGE, 
 	s.LENGTH