SELECT 
    COUNCIL.COMPREHENSIVE_BLEND_CA.SPECIES_GROUP_CODE AS SPECIES,
    COUNCIL.COMPREHENSIVE_BLEND_CA.RETAINED_OR_DISCARDED,
    SUM(COUNCIL.COMPREHENSIVE_BLEND_CA.WEIGHT_POSTED)AS TONS,
    to_char(COUNCIL.COMPREHENSIVE_BLEND_CA.WEEK_END_DATE,'MM') AS MONTH_WED,
    COUNCIL.COMPREHENSIVE_BLEND_CA.FMP_GEAR AS GEAR, 
    COUNCIL.COMPREHENSIVE_BLEND_CA.YEAR AS YEAR, 
    COUNCIL.COMPREHENSIVE_BLEND_CA.REPORTING_AREA_CODE AS AREA,
    'DOMESTIC' AS SOURCE 
FROM COUNCIL.COMPREHENSIVE_BLEND_CA 
WHERE COUNCIL.COMPREHENSIVE_BLEND_CA.FMP_SUBAREA
         -- insert subarea 
      AND COUNCIL.COMPREHENSIVE_BLEND_CA.YEAR 
         -- insert years
      AND COUNCIL.COMPREHENSIVE_BLEND_CA.SPECIES_GROUP_CODE 
         -- insert species_catch
GROUP BY 
      COUNCIL.COMPREHENSIVE_BLEND_CA.SPECIES_GROUP_CODE,
      COUNCIL.COMPREHENSIVE_BLEND_CA.YEAR,
      COUNCIL.COMPREHENSIVE_BLEND_CA.RETAINED_OR_DISCARDED,
      to_char(COUNCIL.COMPREHENSIVE_BLEND_CA.WEEK_END_DATE,'MM'), 
      COUNCIL.COMPREHENSIVE_BLEND_CA.REPORTING_AREA_CODE,
      COUNCIL.COMPREHENSIVE_BLEND_CA.FMP_GEAR
ORDER BY
      COUNCIL.COMPREHENSIVE_BLEND_CA.SPECIES_GROUP_CODE,
      COUNCIL.COMPREHENSIVE_BLEND_CA.YEAR,
      COUNCIL.COMPREHENSIVE_BLEND_CA.RETAINED_OR_DISCARDED,
      to_char(COUNCIL.COMPREHENSIVE_BLEND_CA.WEEK_END_DATE,'MM'), 
      COUNCIL.COMPREHENSIVE_BLEND_CA.REPORTING_AREA_CODE,
      COUNCIL.COMPREHENSIVE_BLEND_CA.FMP_GEAR
