SELECT OBSINT.CURRENT_SPCOMP.SPECIES,
  CAST(OBSINT.CURRENT_HAUL.HAUL_JOIN AS VARCHAR(20)) AS HAUL_JOIN,
  OBSINT.CURRENT_HAUL.CRUISE,
  OBSINT.CURRENT_HAUL.VESSEL,
  OBSINT.CURRENT_HAUL.GEAR_TYPE,
  OBSINT.CURRENT_HAUL.VESSEL_TYPE,
  OBSINT.CURRENT_SPCOMP.YEAR,
  OBSINT.CURRENT_HAUL.NMFS_AREA,
  OBSINT.CURRENT_SPCOMP.SAMPLE_TYPE,
  OBSINT.CURRENT_SPCOMP.SAMPLE_NUMBER,
  OBSINT.CURRENT_SPCOMP.SAMPLE_SIZE,
  OBSINT.CURRENT_SPCOMP.SAMPLE_WEIGHT,
  OBSINT.CURRENT_SPCOMP.WEIGHT,
  OBSINT.CURRENT_SPCOMP.COUNT,
  OBSINT.CURRENT_HAUL.OFFICIAL_TOTAL_CATCH,
  OBSINT.CURRENT_HAUL.DEPLOYMENT_DATE,
  OBSINT.CURRENT_HAUL.RETRIEVAL_DATE,
  to_char(OBSINT.CURRENT_HAUL.RETRIEVAL_DATE,'mm') as MONTH,
  OBSINT.CURRENT_HAUL.TOTAL_HOOKS_POTS,
  OBSINT.CURRENT_HAUL.LATDD_END,
  OBSINT.CURRENT_HAUL.LONDD_END,
  OBSINT.CURRENT_HAUL.BOTTOM_DEPTH_FATHOMS
FROM OBSINT.CURRENT_HAUL
INNER JOIN OBSINT.CURRENT_SPCOMP
ON OBSINT.CURRENT_HAUL.CRUISE       = OBSINT.CURRENT_SPCOMP.CRUISE
AND OBSINT.CURRENT_HAUL.PERMIT      = OBSINT.CURRENT_SPCOMP.PERMIT
AND OBSINT.CURRENT_HAUL.HAUL_SEQ    = OBSINT.CURRENT_SPCOMP.HAUL_SEQ
WHERE OBSINT.CURRENT_SPCOMP.SPECIES 
   -- insert species
